# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-03 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptofolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressinput',
            name='address',
            field=models.CharField(max_length=111),
        ),
    ]
