# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptofolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressinput',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
