# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-13 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptofolio', '0020_auto_20180213_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='timestamp',
        ),
    ]
